/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AddCollaboratorOption model module.
 * @module model/AddCollaboratorOption
 * @version 1.15.6a+dcs
 */
export class AddCollaboratorOption {
  /**
   * Constructs a new <code>AddCollaboratorOption</code>.
   * AddCollaboratorOption options when adding a user as a collaborator of a repository
   * @alias module:model/AddCollaboratorOption
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AddCollaboratorOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddCollaboratorOption} obj Optional instance to populate.
   * @return {module:model/AddCollaboratorOption} The populated <code>AddCollaboratorOption</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AddCollaboratorOption();
      if (data.hasOwnProperty('permission'))
        obj.permission = ApiClient.convertToType(data['permission'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} permission
 */
AddCollaboratorOption.prototype.permission = undefined;

