/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AddTimeOption model module.
 * @module model/AddTimeOption
 * @version 1.15.6a+dcs
 */
export class AddTimeOption {
  /**
   * Constructs a new <code>AddTimeOption</code>.
   * AddTimeOption options for adding time to an issue
   * @alias module:model/AddTimeOption
   * @class
   * @param time {Number} time in seconds
   */
  constructor(time) {
    this.time = time;
  }

  /**
   * Constructs a <code>AddTimeOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddTimeOption} obj Optional instance to populate.
   * @return {module:model/AddTimeOption} The populated <code>AddTimeOption</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AddTimeOption();
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('time'))
        obj.time = ApiClient.convertToType(data['time'], 'Number');
      if (data.hasOwnProperty('user_name'))
        obj.userName = ApiClient.convertToType(data['user_name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Date} created
 */
AddTimeOption.prototype.created = undefined;

/**
 * time in seconds
 * @member {Number} time
 */
AddTimeOption.prototype.time = undefined;

/**
 * User who spent the time (optional)
 * @member {String} userName
 */
AddTimeOption.prototype.userName = undefined;

