/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AnnotatedTagObject model module.
 * @module model/AnnotatedTagObject
 * @version 1.15.6a+dcs
 */
export class AnnotatedTagObject {
  /**
   * Constructs a new <code>AnnotatedTagObject</code>.
   * AnnotatedTagObject contains meta information of the tag object
   * @alias module:model/AnnotatedTagObject
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AnnotatedTagObject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AnnotatedTagObject} obj Optional instance to populate.
   * @return {module:model/AnnotatedTagObject} The populated <code>AnnotatedTagObject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AnnotatedTagObject();
      if (data.hasOwnProperty('sha'))
        obj.sha = ApiClient.convertToType(data['sha'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} sha
 */
AnnotatedTagObject.prototype.sha = undefined;

/**
 * @member {String} type
 */
AnnotatedTagObject.prototype.type = undefined;

/**
 * @member {String} url
 */
AnnotatedTagObject.prototype.url = undefined;

