/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CommitStatusState model module.
 * @module model/CommitStatusState
 * @version 1.15.6a+dcs
 */
export class CommitStatusState {
  /**
   * Constructs a new <code>CommitStatusState</code>.
   * CommitStatusState holds the state of a CommitStatus It can be \&quot;pending\&quot;, \&quot;success\&quot;, \&quot;error\&quot;, \&quot;failure\&quot;, and \&quot;warning\&quot;
   * @alias module:model/CommitStatusState
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CommitStatusState</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CommitStatusState} obj Optional instance to populate.
   * @return {module:model/CommitStatusState} The populated <code>CommitStatusState</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CommitStatusState();
    }
    return obj;
  }
}
