/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CommitMeta model module.
 * @module model/CommitMeta
 * @version 1.15.6a+dcs
 */
export class CommitMeta {
  /**
   * Constructs a new <code>CommitMeta</code>.
   * @alias module:model/CommitMeta
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CommitMeta</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CommitMeta} obj Optional instance to populate.
   * @return {module:model/CommitMeta} The populated <code>CommitMeta</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CommitMeta();
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('sha'))
        obj.sha = ApiClient.convertToType(data['sha'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Date} created
 */
CommitMeta.prototype.created = undefined;

/**
 * @member {String} sha
 */
CommitMeta.prototype.sha = undefined;

/**
 * @member {String} url
 */
CommitMeta.prototype.url = undefined;

