/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CommitUser model module.
 * @module model/CommitUser
 * @version 1.15.6a+dcs
 */
export class CommitUser {
  /**
   * Constructs a new <code>CommitUser</code>.
   * @alias module:model/CommitUser
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CommitUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CommitUser} obj Optional instance to populate.
   * @return {module:model/CommitUser} The populated <code>CommitUser</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CommitUser();
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} _date
 */
CommitUser.prototype._date = undefined;

/**
 * @member {String} email
 */
CommitUser.prototype.email = undefined;

/**
 * @member {String} name
 */
CommitUser.prototype.name = undefined;

