/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateTeamOption model module.
 * @module model/CreateTeamOption
 * @version 1.15.6a+dcs
 */
export class CreateTeamOption {
  /**
   * Constructs a new <code>CreateTeamOption</code>.
   * CreateTeamOption options for creating a team
   * @alias module:model/CreateTeamOption
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>CreateTeamOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateTeamOption} obj Optional instance to populate.
   * @return {module:model/CreateTeamOption} The populated <code>CreateTeamOption</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateTeamOption();
      if (data.hasOwnProperty('can_create_org_repo'))
        obj.canCreateOrgRepo = ApiClient.convertToType(data['can_create_org_repo'], 'Boolean');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('includes_all_repositories'))
        obj.includesAllRepositories = ApiClient.convertToType(data['includes_all_repositories'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('permission'))
        obj.permission = ApiClient.convertToType(data['permission'], 'String');
      if (data.hasOwnProperty('units'))
        obj.units = ApiClient.convertToType(data['units'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Boolean} canCreateOrgRepo
 */
CreateTeamOption.prototype.canCreateOrgRepo = undefined;

/**
 * @member {String} description
 */
CreateTeamOption.prototype.description = undefined;

/**
 * @member {Boolean} includesAllRepositories
 */
CreateTeamOption.prototype.includesAllRepositories = undefined;

/**
 * @member {String} name
 */
CreateTeamOption.prototype.name = undefined;

/**
 * Allowed values for the <code>permission</code> property.
 * @enum {String}
 * @readonly
 */
CreateTeamOption.PermissionEnum = {
  /**
   * value: "read"
   * @const
   */
  read: "read",

  /**
   * value: "write"
   * @const
   */
  write: "write",

  /**
   * value: "admin"
   * @const
   */
  admin: "admin"
};
/**
 * @member {module:model/CreateTeamOption.PermissionEnum} permission
 */
CreateTeamOption.prototype.permission = undefined;

/**
 * @member {Array.<String>} units
 */
CreateTeamOption.prototype.units = undefined;

