/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateMilestoneOption model module.
 * @module model/CreateMilestoneOption
 * @version 1.15.6a+dcs
 */
export class CreateMilestoneOption {
  /**
   * Constructs a new <code>CreateMilestoneOption</code>.
   * CreateMilestoneOption options for creating a milestone
   * @alias module:model/CreateMilestoneOption
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateMilestoneOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateMilestoneOption} obj Optional instance to populate.
   * @return {module:model/CreateMilestoneOption} The populated <code>CreateMilestoneOption</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateMilestoneOption();
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('due_on'))
        obj.dueOn = ApiClient.convertToType(data['due_on'], 'Date');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} description
 */
CreateMilestoneOption.prototype.description = undefined;

/**
 * @member {Date} dueOn
 */
CreateMilestoneOption.prototype.dueOn = undefined;

/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
CreateMilestoneOption.StateEnum = {
  /**
   * value: "open"
   * @const
   */
  open: "open",

  /**
   * value: "closed"
   * @const
   */
  closed: "closed"
};
/**
 * @member {module:model/CreateMilestoneOption.StateEnum} state
 */
CreateMilestoneOption.prototype.state = undefined;

/**
 * @member {String} title
 */
CreateMilestoneOption.prototype.title = undefined;

