/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateAccessTokenOption model module.
 * @module model/CreateAccessTokenOption
 * @version 1.15.6a+dcs
 */
export class CreateAccessTokenOption {
  /**
   * Constructs a new <code>CreateAccessTokenOption</code>.
   * CreateAccessTokenOption options when create access token
   * @alias module:model/CreateAccessTokenOption
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateAccessTokenOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateAccessTokenOption} obj Optional instance to populate.
   * @return {module:model/CreateAccessTokenOption} The populated <code>CreateAccessTokenOption</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateAccessTokenOption();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} name
 */
CreateAccessTokenOption.prototype.name = undefined;

