/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateGPGKeyOption model module.
 * @module model/CreateGPGKeyOption
 * @version 1.15.6a+dcs
 */
export class CreateGPGKeyOption {
  /**
   * Constructs a new <code>CreateGPGKeyOption</code>.
   * CreateGPGKeyOption options create user GPG key
   * @alias module:model/CreateGPGKeyOption
   * @class
   * @param armoredPublicKey {String} An armored GPG key to add
   */
  constructor(armoredPublicKey) {
    this.armoredPublicKey = armoredPublicKey;
  }

  /**
   * Constructs a <code>CreateGPGKeyOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateGPGKeyOption} obj Optional instance to populate.
   * @return {module:model/CreateGPGKeyOption} The populated <code>CreateGPGKeyOption</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateGPGKeyOption();
      if (data.hasOwnProperty('armored_public_key'))
        obj.armoredPublicKey = ApiClient.convertToType(data['armored_public_key'], 'String');
      if (data.hasOwnProperty('armored_signature'))
        obj.armoredSignature = ApiClient.convertToType(data['armored_signature'], 'String');
    }
    return obj;
  }
}

/**
 * An armored GPG key to add
 * @member {String} armoredPublicKey
 */
CreateGPGKeyOption.prototype.armoredPublicKey = undefined;

/**
 * @member {String} armoredSignature
 */
CreateGPGKeyOption.prototype.armoredSignature = undefined;

