/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateEmailOption model module.
 * @module model/CreateEmailOption
 * @version 1.15.6a+dcs
 */
export class CreateEmailOption {
  /**
   * Constructs a new <code>CreateEmailOption</code>.
   * CreateEmailOption options when creating email addresses
   * @alias module:model/CreateEmailOption
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CreateEmailOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateEmailOption} obj Optional instance to populate.
   * @return {module:model/CreateEmailOption} The populated <code>CreateEmailOption</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateEmailOption();
      if (data.hasOwnProperty('emails'))
        obj.emails = ApiClient.convertToType(data['emails'], ['String']);
    }
    return obj;
  }
}

/**
 * email addresses to add
 * @member {Array.<String>} emails
 */
CreateEmailOption.prototype.emails = undefined;

