/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CreateReleaseOption model module.
 * @module model/CreateReleaseOption
 * @version 1.15.6a+dcs
 */
export class CreateReleaseOption {
  /**
   * Constructs a new <code>CreateReleaseOption</code>.
   * CreateReleaseOption options when creating a release
   * @alias module:model/CreateReleaseOption
   * @class
   * @param tagName {String} 
   */
  constructor(tagName) {
    this.tagName = tagName;
  }

  /**
   * Constructs a <code>CreateReleaseOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CreateReleaseOption} obj Optional instance to populate.
   * @return {module:model/CreateReleaseOption} The populated <code>CreateReleaseOption</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CreateReleaseOption();
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], 'String');
      if (data.hasOwnProperty('draft'))
        obj.draft = ApiClient.convertToType(data['draft'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('prerelease'))
        obj.prerelease = ApiClient.convertToType(data['prerelease'], 'Boolean');
      if (data.hasOwnProperty('tag_name'))
        obj.tagName = ApiClient.convertToType(data['tag_name'], 'String');
      if (data.hasOwnProperty('target_commitish'))
        obj.targetCommitish = ApiClient.convertToType(data['target_commitish'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} body
 */
CreateReleaseOption.prototype.body = undefined;

/**
 * @member {Boolean} draft
 */
CreateReleaseOption.prototype.draft = undefined;

/**
 * @member {String} name
 */
CreateReleaseOption.prototype.name = undefined;

/**
 * @member {Boolean} prerelease
 */
CreateReleaseOption.prototype.prerelease = undefined;

/**
 * @member {String} tagName
 */
CreateReleaseOption.prototype.tagName = undefined;

/**
 * @member {String} targetCommitish
 */
CreateReleaseOption.prototype.targetCommitish = undefined;

