/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The EditReactionOption model module.
 * @module model/EditReactionOption
 * @version 1.15.6a+dcs
 */
export class EditReactionOption {
  /**
   * Constructs a new <code>EditReactionOption</code>.
   * EditReactionOption contain the reaction type
   * @alias module:model/EditReactionOption
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EditReactionOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EditReactionOption} obj Optional instance to populate.
   * @return {module:model/EditReactionOption} The populated <code>EditReactionOption</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EditReactionOption();
      if (data.hasOwnProperty('content'))
        obj.content = ApiClient.convertToType(data['content'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} content
 */
EditReactionOption.prototype.content = undefined;

