/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The EditReleaseOption model module.
 * @module model/EditReleaseOption
 * @version 1.15.6a+dcs
 */
export class EditReleaseOption {
  /**
   * Constructs a new <code>EditReleaseOption</code>.
   * EditReleaseOption options when editing a release
   * @alias module:model/EditReleaseOption
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EditReleaseOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EditReleaseOption} obj Optional instance to populate.
   * @return {module:model/EditReleaseOption} The populated <code>EditReleaseOption</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EditReleaseOption();
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], 'String');
      if (data.hasOwnProperty('draft'))
        obj.draft = ApiClient.convertToType(data['draft'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('prerelease'))
        obj.prerelease = ApiClient.convertToType(data['prerelease'], 'Boolean');
      if (data.hasOwnProperty('tag_name'))
        obj.tagName = ApiClient.convertToType(data['tag_name'], 'String');
      if (data.hasOwnProperty('target_commitish'))
        obj.targetCommitish = ApiClient.convertToType(data['target_commitish'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} body
 */
EditReleaseOption.prototype.body = undefined;

/**
 * @member {Boolean} draft
 */
EditReleaseOption.prototype.draft = undefined;

/**
 * @member {String} name
 */
EditReleaseOption.prototype.name = undefined;

/**
 * @member {Boolean} prerelease
 */
EditReleaseOption.prototype.prerelease = undefined;

/**
 * @member {String} tagName
 */
EditReleaseOption.prototype.tagName = undefined;

/**
 * @member {String} targetCommitish
 */
EditReleaseOption.prototype.targetCommitish = undefined;

