/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The EditPullRequestOption model module.
 * @module model/EditPullRequestOption
 * @version 1.15.6a+dcs
 */
export class EditPullRequestOption {
  /**
   * Constructs a new <code>EditPullRequestOption</code>.
   * EditPullRequestOption options when modify pull request
   * @alias module:model/EditPullRequestOption
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>EditPullRequestOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EditPullRequestOption} obj Optional instance to populate.
   * @return {module:model/EditPullRequestOption} The populated <code>EditPullRequestOption</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EditPullRequestOption();
      if (data.hasOwnProperty('assignee'))
        obj.assignee = ApiClient.convertToType(data['assignee'], 'String');
      if (data.hasOwnProperty('assignees'))
        obj.assignees = ApiClient.convertToType(data['assignees'], ['String']);
      if (data.hasOwnProperty('base'))
        obj.base = ApiClient.convertToType(data['base'], 'String');
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], 'String');
      if (data.hasOwnProperty('due_date'))
        obj.dueDate = ApiClient.convertToType(data['due_date'], 'Date');
      if (data.hasOwnProperty('labels'))
        obj.labels = ApiClient.convertToType(data['labels'], ['Number']);
      if (data.hasOwnProperty('milestone'))
        obj.milestone = ApiClient.convertToType(data['milestone'], 'Number');
      if (data.hasOwnProperty('state'))
        obj.state = ApiClient.convertToType(data['state'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('unset_due_date'))
        obj.unsetDueDate = ApiClient.convertToType(data['unset_due_date'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {String} assignee
 */
EditPullRequestOption.prototype.assignee = undefined;

/**
 * @member {Array.<String>} assignees
 */
EditPullRequestOption.prototype.assignees = undefined;

/**
 * @member {String} base
 */
EditPullRequestOption.prototype.base = undefined;

/**
 * @member {String} body
 */
EditPullRequestOption.prototype.body = undefined;

/**
 * @member {Date} dueDate
 */
EditPullRequestOption.prototype.dueDate = undefined;

/**
 * @member {Array.<Number>} labels
 */
EditPullRequestOption.prototype.labels = undefined;

/**
 * @member {Number} milestone
 */
EditPullRequestOption.prototype.milestone = undefined;

/**
 * @member {String} state
 */
EditPullRequestOption.prototype.state = undefined;

/**
 * @member {String} title
 */
EditPullRequestOption.prototype.title = undefined;

/**
 * @member {Boolean} unsetDueDate
 */
EditPullRequestOption.prototype.unsetDueDate = undefined;

