/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The EditTeamOption model module.
 * @module model/EditTeamOption
 * @version 1.15.6a+dcs
 */
export class EditTeamOption {
  /**
   * Constructs a new <code>EditTeamOption</code>.
   * EditTeamOption options for editing a team
   * @alias module:model/EditTeamOption
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>EditTeamOption</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/EditTeamOption} obj Optional instance to populate.
   * @return {module:model/EditTeamOption} The populated <code>EditTeamOption</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new EditTeamOption();
      if (data.hasOwnProperty('can_create_org_repo'))
        obj.canCreateOrgRepo = ApiClient.convertToType(data['can_create_org_repo'], 'Boolean');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('includes_all_repositories'))
        obj.includesAllRepositories = ApiClient.convertToType(data['includes_all_repositories'], 'Boolean');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('permission'))
        obj.permission = ApiClient.convertToType(data['permission'], 'String');
      if (data.hasOwnProperty('units'))
        obj.units = ApiClient.convertToType(data['units'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Boolean} canCreateOrgRepo
 */
EditTeamOption.prototype.canCreateOrgRepo = undefined;

/**
 * @member {String} description
 */
EditTeamOption.prototype.description = undefined;

/**
 * @member {Boolean} includesAllRepositories
 */
EditTeamOption.prototype.includesAllRepositories = undefined;

/**
 * @member {String} name
 */
EditTeamOption.prototype.name = undefined;

/**
 * Allowed values for the <code>permission</code> property.
 * @enum {String}
 * @readonly
 */
EditTeamOption.PermissionEnum = {
  /**
   * value: "read"
   * @const
   */
  read: "read",

  /**
   * value: "write"
   * @const
   */
  write: "write",

  /**
   * value: "admin"
   * @const
   */
  admin: "admin"
};
/**
 * @member {module:model/EditTeamOption.PermissionEnum} permission
 */
EditTeamOption.prototype.permission = undefined;

/**
 * @member {Array.<String>} units
 */
EditTeamOption.prototype.units = undefined;

