/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ExternalWiki model module.
 * @module model/ExternalWiki
 * @version 1.15.6a+dcs
 */
export class ExternalWiki {
  /**
   * Constructs a new <code>ExternalWiki</code>.
   * ExternalWiki represents setting for external wiki
   * @alias module:model/ExternalWiki
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ExternalWiki</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ExternalWiki} obj Optional instance to populate.
   * @return {module:model/ExternalWiki} The populated <code>ExternalWiki</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ExternalWiki();
      if (data.hasOwnProperty('external_wiki_url'))
        obj.externalWikiUrl = ApiClient.convertToType(data['external_wiki_url'], 'String');
    }
    return obj;
  }
}

/**
 * URL of external wiki.
 * @member {String} externalWikiUrl
 */
ExternalWiki.prototype.externalWikiUrl = undefined;

