/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ContentsResponse} from './ContentsResponse';
import {FileCommitResponse} from './FileCommitResponse';
import {PayloadCommitVerification} from './PayloadCommitVerification';

/**
 * The FileResponse model module.
 * @module model/FileResponse
 * @version 1.15.6a+dcs
 */
export class FileResponse {
  /**
   * Constructs a new <code>FileResponse</code>.
   * FileResponse contains information about a repo&#x27;s file
   * @alias module:model/FileResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FileResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FileResponse} obj Optional instance to populate.
   * @return {module:model/FileResponse} The populated <code>FileResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FileResponse();
      if (data.hasOwnProperty('commit'))
        obj.commit = FileCommitResponse.constructFromObject(data['commit']);
      if (data.hasOwnProperty('content'))
        obj.content = ContentsResponse.constructFromObject(data['content']);
      if (data.hasOwnProperty('verification'))
        obj.verification = PayloadCommitVerification.constructFromObject(data['verification']);
    }
    return obj;
  }
}

/**
 * @member {module:model/FileCommitResponse} commit
 */
FileResponse.prototype.commit = undefined;

/**
 * @member {module:model/ContentsResponse} content
 */
FileResponse.prototype.content = undefined;

/**
 * @member {module:model/PayloadCommitVerification} verification
 */
FileResponse.prototype.verification = undefined;

