/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GitEntry} from './GitEntry';

/**
 * The GitTreeResponse model module.
 * @module model/GitTreeResponse
 * @version 1.15.6a+dcs
 */
export class GitTreeResponse {
  /**
   * Constructs a new <code>GitTreeResponse</code>.
   * GitTreeResponse returns a git tree
   * @alias module:model/GitTreeResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GitTreeResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GitTreeResponse} obj Optional instance to populate.
   * @return {module:model/GitTreeResponse} The populated <code>GitTreeResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GitTreeResponse();
      if (data.hasOwnProperty('page'))
        obj.page = ApiClient.convertToType(data['page'], 'Number');
      if (data.hasOwnProperty('sha'))
        obj.sha = ApiClient.convertToType(data['sha'], 'String');
      if (data.hasOwnProperty('total_count'))
        obj.totalCount = ApiClient.convertToType(data['total_count'], 'Number');
      if (data.hasOwnProperty('tree'))
        obj.tree = ApiClient.convertToType(data['tree'], [GitEntry]);
      if (data.hasOwnProperty('truncated'))
        obj.truncated = ApiClient.convertToType(data['truncated'], 'Boolean');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} page
 */
GitTreeResponse.prototype.page = undefined;

/**
 * @member {String} sha
 */
GitTreeResponse.prototype.sha = undefined;

/**
 * @member {Number} totalCount
 */
GitTreeResponse.prototype.totalCount = undefined;

/**
 * @member {Array.<module:model/GitEntry>} tree
 */
GitTreeResponse.prototype.tree = undefined;

/**
 * @member {Boolean} truncated
 */
GitTreeResponse.prototype.truncated = undefined;

/**
 * @member {String} url
 */
GitTreeResponse.prototype.url = undefined;

