/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {GPGKeyEmail} from './GPGKeyEmail';

/**
 * The GPGKey model module.
 * @module model/GPGKey
 * @version 1.15.6a+dcs
 */
export class GPGKey {
  /**
   * Constructs a new <code>GPGKey</code>.
   * GPGKey a user GPG key to sign commit and tag in repository
   * @alias module:model/GPGKey
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>GPGKey</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GPGKey} obj Optional instance to populate.
   * @return {module:model/GPGKey} The populated <code>GPGKey</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new GPGKey();
      if (data.hasOwnProperty('can_certify'))
        obj.canCertify = ApiClient.convertToType(data['can_certify'], 'Boolean');
      if (data.hasOwnProperty('can_encrypt_comms'))
        obj.canEncryptComms = ApiClient.convertToType(data['can_encrypt_comms'], 'Boolean');
      if (data.hasOwnProperty('can_encrypt_storage'))
        obj.canEncryptStorage = ApiClient.convertToType(data['can_encrypt_storage'], 'Boolean');
      if (data.hasOwnProperty('can_sign'))
        obj.canSign = ApiClient.convertToType(data['can_sign'], 'Boolean');
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'Date');
      if (data.hasOwnProperty('emails'))
        obj.emails = ApiClient.convertToType(data['emails'], [GPGKeyEmail]);
      if (data.hasOwnProperty('expires_at'))
        obj.expiresAt = ApiClient.convertToType(data['expires_at'], 'Date');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('key_id'))
        obj.keyId = ApiClient.convertToType(data['key_id'], 'String');
      if (data.hasOwnProperty('primary_key_id'))
        obj.primaryKeyId = ApiClient.convertToType(data['primary_key_id'], 'String');
      if (data.hasOwnProperty('public_key'))
        obj.publicKey = ApiClient.convertToType(data['public_key'], 'String');
      if (data.hasOwnProperty('subkeys'))
        obj.subkeys = ApiClient.convertToType(data['subkeys'], [GPGKey]);
      if (data.hasOwnProperty('verified'))
        obj.verified = ApiClient.convertToType(data['verified'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {Boolean} canCertify
 */
GPGKey.prototype.canCertify = undefined;

/**
 * @member {Boolean} canEncryptComms
 */
GPGKey.prototype.canEncryptComms = undefined;

/**
 * @member {Boolean} canEncryptStorage
 */
GPGKey.prototype.canEncryptStorage = undefined;

/**
 * @member {Boolean} canSign
 */
GPGKey.prototype.canSign = undefined;

/**
 * @member {Date} createdAt
 */
GPGKey.prototype.createdAt = undefined;

/**
 * @member {Array.<module:model/GPGKeyEmail>} emails
 */
GPGKey.prototype.emails = undefined;

/**
 * @member {Date} expiresAt
 */
GPGKey.prototype.expiresAt = undefined;

/**
 * @member {Number} id
 */
GPGKey.prototype.id = undefined;

/**
 * @member {String} keyId
 */
GPGKey.prototype.keyId = undefined;

/**
 * @member {String} primaryKeyId
 */
GPGKey.prototype.primaryKeyId = undefined;

/**
 * @member {String} publicKey
 */
GPGKey.prototype.publicKey = undefined;

/**
 * @member {Array.<module:model/GPGKey>} subkeys
 */
GPGKey.prototype.subkeys = undefined;

/**
 * @member {Boolean} verified
 */
GPGKey.prototype.verified = undefined;

