/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The NotificationCount model module.
 * @module model/NotificationCount
 * @version 1.15.6a+dcs
 */
export class NotificationCount {
  /**
   * Constructs a new <code>NotificationCount</code>.
   * NotificationCount number of unread notifications
   * @alias module:model/NotificationCount
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>NotificationCount</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NotificationCount} obj Optional instance to populate.
   * @return {module:model/NotificationCount} The populated <code>NotificationCount</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NotificationCount();
      if (data.hasOwnProperty('new'))
        obj._new = ApiClient.convertToType(data['new'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Number} _new
 */
NotificationCount.prototype._new = undefined;

