/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {NotifySubjectType} from './NotifySubjectType';
import {StateType} from './StateType';

/**
 * The NotificationSubject model module.
 * @module model/NotificationSubject
 * @version 1.15.6a+dcs
 */
export class NotificationSubject {
  /**
   * Constructs a new <code>NotificationSubject</code>.
   * NotificationSubject contains the notification subject (Issue/Pull/Commit)
   * @alias module:model/NotificationSubject
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>NotificationSubject</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NotificationSubject} obj Optional instance to populate.
   * @return {module:model/NotificationSubject} The populated <code>NotificationSubject</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new NotificationSubject();
      if (data.hasOwnProperty('latest_comment_url'))
        obj.latestCommentUrl = ApiClient.convertToType(data['latest_comment_url'], 'String');
      if (data.hasOwnProperty('state'))
        obj.state = StateType.constructFromObject(data['state']);
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = NotifySubjectType.constructFromObject(data['type']);
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} latestCommentUrl
 */
NotificationSubject.prototype.latestCommentUrl = undefined;

/**
 * @member {module:model/StateType} state
 */
NotificationSubject.prototype.state = undefined;

/**
 * @member {String} title
 */
NotificationSubject.prototype.title = undefined;

/**
 * @member {module:model/NotifySubjectType} type
 */
NotificationSubject.prototype.type = undefined;

/**
 * @member {String} url
 */
NotificationSubject.prototype.url = undefined;

