/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The OAuth2Application model module.
 * @module model/OAuth2Application
 * @version 1.15.6a+dcs
 */
export class OAuth2Application {
  /**
   * Constructs a new <code>OAuth2Application</code>.
   * @alias module:model/OAuth2Application
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>OAuth2Application</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/OAuth2Application} obj Optional instance to populate.
   * @return {module:model/OAuth2Application} The populated <code>OAuth2Application</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new OAuth2Application();
      if (data.hasOwnProperty('client_id'))
        obj.clientId = ApiClient.convertToType(data['client_id'], 'String');
      if (data.hasOwnProperty('client_secret'))
        obj.clientSecret = ApiClient.convertToType(data['client_secret'], 'String');
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('redirect_uris'))
        obj.redirectUris = ApiClient.convertToType(data['redirect_uris'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {String} clientId
 */
OAuth2Application.prototype.clientId = undefined;

/**
 * @member {String} clientSecret
 */
OAuth2Application.prototype.clientSecret = undefined;

/**
 * @member {Date} created
 */
OAuth2Application.prototype.created = undefined;

/**
 * @member {Number} id
 */
OAuth2Application.prototype.id = undefined;

/**
 * @member {String} name
 */
OAuth2Application.prototype.name = undefined;

/**
 * @member {Array.<String>} redirectUris
 */
OAuth2Application.prototype.redirectUris = undefined;

