/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Organization model module.
 * @module model/Organization
 * @version 1.15.6a+dcs
 */
export class Organization {
  /**
   * Constructs a new <code>Organization</code>.
   * Organization represents an organization
   * @alias module:model/Organization
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Organization</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Organization} obj Optional instance to populate.
   * @return {module:model/Organization} The populated <code>Organization</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Organization();
      if (data.hasOwnProperty('avatar_url'))
        obj.avatarUrl = ApiClient.convertToType(data['avatar_url'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('full_name'))
        obj.fullName = ApiClient.convertToType(data['full_name'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('repo_admin_change_team_access'))
        obj.repoAdminChangeTeamAccess = ApiClient.convertToType(data['repo_admin_change_team_access'], 'Boolean');
      if (data.hasOwnProperty('repo_languages'))
        obj.repoLanguages = ApiClient.convertToType(data['repo_languages'], ['String']);
      if (data.hasOwnProperty('repo_subjects'))
        obj.repoSubjects = ApiClient.convertToType(data['repo_subjects'], ['String']);
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('visibility'))
        obj.visibility = ApiClient.convertToType(data['visibility'], 'String');
      if (data.hasOwnProperty('website'))
        obj.website = ApiClient.convertToType(data['website'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} avatarUrl
 */
Organization.prototype.avatarUrl = undefined;

/**
 * @member {String} description
 */
Organization.prototype.description = undefined;

/**
 * @member {String} fullName
 */
Organization.prototype.fullName = undefined;

/**
 * @member {Number} id
 */
Organization.prototype.id = undefined;

/**
 * @member {String} location
 */
Organization.prototype.location = undefined;

/**
 * @member {Boolean} repoAdminChangeTeamAccess
 */
Organization.prototype.repoAdminChangeTeamAccess = undefined;

/**
 * DCS Customizations ***_/
 * @member {Array.<String>} repoLanguages
 */
Organization.prototype.repoLanguages = undefined;

/**
 * @member {Array.<String>} repoSubjects
 */
Organization.prototype.repoSubjects = undefined;

/**
 * @member {String} username
 */
Organization.prototype.username = undefined;

/**
 * @member {String} visibility
 */
Organization.prototype.visibility = undefined;

/**
 * @member {String} website
 */
Organization.prototype.website = undefined;

