/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The PullReviewRequestOptions model module.
 * @module model/PullReviewRequestOptions
 * @version 1.15.6a+dcs
 */
export class PullReviewRequestOptions {
  /**
   * Constructs a new <code>PullReviewRequestOptions</code>.
   * PullReviewRequestOptions are options to add or remove pull review requests
   * @alias module:model/PullReviewRequestOptions
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PullReviewRequestOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PullReviewRequestOptions} obj Optional instance to populate.
   * @return {module:model/PullReviewRequestOptions} The populated <code>PullReviewRequestOptions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PullReviewRequestOptions();
      if (data.hasOwnProperty('reviewers'))
        obj.reviewers = ApiClient.convertToType(data['reviewers'], ['String']);
      if (data.hasOwnProperty('team_reviewers'))
        obj.teamReviewers = ApiClient.convertToType(data['team_reviewers'], ['String']);
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} reviewers
 */
PullReviewRequestOptions.prototype.reviewers = undefined;

/**
 * @member {Array.<String>} teamReviewers
 */
PullReviewRequestOptions.prototype.teamReviewers = undefined;

