/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The RepoTopicOptions model module.
 * @module model/RepoTopicOptions
 * @version 1.15.6a+dcs
 */
export class RepoTopicOptions {
  /**
   * Constructs a new <code>RepoTopicOptions</code>.
   * RepoTopicOptions a collection of repo topic names
   * @alias module:model/RepoTopicOptions
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>RepoTopicOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/RepoTopicOptions} obj Optional instance to populate.
   * @return {module:model/RepoTopicOptions} The populated <code>RepoTopicOptions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new RepoTopicOptions();
      if (data.hasOwnProperty('topics'))
        obj.topics = ApiClient.convertToType(data['topics'], ['String']);
    }
    return obj;
  }
}

/**
 * list of topic names
 * @member {Array.<String>} topics
 */
RepoTopicOptions.prototype.topics = undefined;

