/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The StopWatch model module.
 * @module model/StopWatch
 * @version 1.15.6a+dcs
 */
export class StopWatch {
  /**
   * Constructs a new <code>StopWatch</code>.
   * StopWatch represent a running stopwatch
   * @alias module:model/StopWatch
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>StopWatch</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/StopWatch} obj Optional instance to populate.
   * @return {module:model/StopWatch} The populated <code>StopWatch</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new StopWatch();
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('duration'))
        obj.duration = ApiClient.convertToType(data['duration'], 'String');
      if (data.hasOwnProperty('issue_index'))
        obj.issueIndex = ApiClient.convertToType(data['issue_index'], 'Number');
      if (data.hasOwnProperty('issue_title'))
        obj.issueTitle = ApiClient.convertToType(data['issue_title'], 'String');
      if (data.hasOwnProperty('repo_name'))
        obj.repoName = ApiClient.convertToType(data['repo_name'], 'String');
      if (data.hasOwnProperty('repo_owner_name'))
        obj.repoOwnerName = ApiClient.convertToType(data['repo_owner_name'], 'String');
      if (data.hasOwnProperty('seconds'))
        obj.seconds = ApiClient.convertToType(data['seconds'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Date} created
 */
StopWatch.prototype.created = undefined;

/**
 * @member {String} duration
 */
StopWatch.prototype.duration = undefined;

/**
 * @member {Number} issueIndex
 */
StopWatch.prototype.issueIndex = undefined;

/**
 * @member {String} issueTitle
 */
StopWatch.prototype.issueTitle = undefined;

/**
 * @member {String} repoName
 */
StopWatch.prototype.repoName = undefined;

/**
 * @member {String} repoOwnerName
 */
StopWatch.prototype.repoOwnerName = undefined;

/**
 * @member {Number} seconds
 */
StopWatch.prototype.seconds = undefined;

