/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {ReviewStateType} from './ReviewStateType';

/**
 * The SubmitPullReviewOptions model module.
 * @module model/SubmitPullReviewOptions
 * @version 1.15.6a+dcs
 */
export class SubmitPullReviewOptions {
  /**
   * Constructs a new <code>SubmitPullReviewOptions</code>.
   * SubmitPullReviewOptions are options to submit a pending pull review
   * @alias module:model/SubmitPullReviewOptions
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>SubmitPullReviewOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubmitPullReviewOptions} obj Optional instance to populate.
   * @return {module:model/SubmitPullReviewOptions} The populated <code>SubmitPullReviewOptions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new SubmitPullReviewOptions();
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], 'String');
      if (data.hasOwnProperty('event'))
        obj.event = ReviewStateType.constructFromObject(data['event']);
    }
    return obj;
  }
}

/**
 * @member {String} body
 */
SubmitPullReviewOptions.prototype.body = undefined;

/**
 * @member {module:model/ReviewStateType} event
 */
SubmitPullReviewOptions.prototype.event = undefined;

