/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TopicResponse model module.
 * @module model/TopicResponse
 * @version 1.15.6a+dcs
 */
export class TopicResponse {
  /**
   * Constructs a new <code>TopicResponse</code>.
   * TopicResponse for returning topics
   * @alias module:model/TopicResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TopicResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TopicResponse} obj Optional instance to populate.
   * @return {module:model/TopicResponse} The populated <code>TopicResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TopicResponse();
      if (data.hasOwnProperty('created'))
        obj.created = ApiClient.convertToType(data['created'], 'Date');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'Number');
      if (data.hasOwnProperty('repo_count'))
        obj.repoCount = ApiClient.convertToType(data['repo_count'], 'Number');
      if (data.hasOwnProperty('topic_name'))
        obj.topicName = ApiClient.convertToType(data['topic_name'], 'String');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {Date} created
 */
TopicResponse.prototype.created = undefined;

/**
 * @member {Number} id
 */
TopicResponse.prototype.id = undefined;

/**
 * @member {Number} repoCount
 */
TopicResponse.prototype.repoCount = undefined;

/**
 * @member {String} topicName
 */
TopicResponse.prototype.topicName = undefined;

/**
 * @member {Date} updated
 */
TopicResponse.prototype.updated = undefined;

