/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The UserSettingsOptions model module.
 * @module model/UserSettingsOptions
 * @version 1.15.6a+dcs
 */
export class UserSettingsOptions {
  /**
   * Constructs a new <code>UserSettingsOptions</code>.
   * UserSettingsOptions represents options to change user settings
   * @alias module:model/UserSettingsOptions
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>UserSettingsOptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserSettingsOptions} obj Optional instance to populate.
   * @return {module:model/UserSettingsOptions} The populated <code>UserSettingsOptions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new UserSettingsOptions();
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('diff_view_style'))
        obj.diffViewStyle = ApiClient.convertToType(data['diff_view_style'], 'String');
      if (data.hasOwnProperty('full_name'))
        obj.fullName = ApiClient.convertToType(data['full_name'], 'String');
      if (data.hasOwnProperty('hide_activity'))
        obj.hideActivity = ApiClient.convertToType(data['hide_activity'], 'Boolean');
      if (data.hasOwnProperty('hide_email'))
        obj.hideEmail = ApiClient.convertToType(data['hide_email'], 'Boolean');
      if (data.hasOwnProperty('language'))
        obj.language = ApiClient.convertToType(data['language'], 'String');
      if (data.hasOwnProperty('location'))
        obj.location = ApiClient.convertToType(data['location'], 'String');
      if (data.hasOwnProperty('theme'))
        obj.theme = ApiClient.convertToType(data['theme'], 'String');
      if (data.hasOwnProperty('website'))
        obj.website = ApiClient.convertToType(data['website'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} description
 */
UserSettingsOptions.prototype.description = undefined;

/**
 * @member {String} diffViewStyle
 */
UserSettingsOptions.prototype.diffViewStyle = undefined;

/**
 * @member {String} fullName
 */
UserSettingsOptions.prototype.fullName = undefined;

/**
 * @member {Boolean} hideActivity
 */
UserSettingsOptions.prototype.hideActivity = undefined;

/**
 * Privacy
 * @member {Boolean} hideEmail
 */
UserSettingsOptions.prototype.hideEmail = undefined;

/**
 * @member {String} language
 */
UserSettingsOptions.prototype.language = undefined;

/**
 * @member {String} location
 */
UserSettingsOptions.prototype.location = undefined;

/**
 * @member {String} theme
 */
UserSettingsOptions.prototype.theme = undefined;

/**
 * @member {String} website
 */
UserSettingsOptions.prototype.website = undefined;

