/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.dcs);
  }
}(this, function(expect, dcs) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('CreateFileOptions', function() {
      beforeEach(function() {
        instance = new dcs.CreateFileOptions();
      });

      it('should create an instance of CreateFileOptions', function() {
        // TODO: update the code to test CreateFileOptions
        expect(instance).to.be.a(dcs.CreateFileOptions);
      });

      it('should have the property author (base name: "author")', function() {
        // TODO: update the code to test the property author
        expect(instance).to.have.property('author');
        // expect(instance.author).to.be(expectedValueLiteral);
      });

      it('should have the property branch (base name: "branch")', function() {
        // TODO: update the code to test the property branch
        expect(instance).to.have.property('branch');
        // expect(instance.branch).to.be(expectedValueLiteral);
      });

      it('should have the property committer (base name: "committer")', function() {
        // TODO: update the code to test the property committer
        expect(instance).to.have.property('committer');
        // expect(instance.committer).to.be(expectedValueLiteral);
      });

      it('should have the property content (base name: "content")', function() {
        // TODO: update the code to test the property content
        expect(instance).to.have.property('content');
        // expect(instance.content).to.be(expectedValueLiteral);
      });

      it('should have the property dates (base name: "dates")', function() {
        // TODO: update the code to test the property dates
        expect(instance).to.have.property('dates');
        // expect(instance.dates).to.be(expectedValueLiteral);
      });

      it('should have the property message (base name: "message")', function() {
        // TODO: update the code to test the property message
        expect(instance).to.have.property('message');
        // expect(instance.message).to.be(expectedValueLiteral);
      });

      it('should have the property newBranch (base name: "new_branch")', function() {
        // TODO: update the code to test the property newBranch
        expect(instance).to.have.property('newBranch');
        // expect(instance.newBranch).to.be(expectedValueLiteral);
      });

      it('should have the property signoff (base name: "signoff")', function() {
        // TODO: update the code to test the property signoff
        expect(instance).to.have.property('signoff');
        // expect(instance.signoff).to.be(expectedValueLiteral);
      });

    });
  });

}));
