/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.dcs);
  }
}(this, function(expect, dcs) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Repository', function() {
      beforeEach(function() {
        instance = new dcs.Repository();
      });

      it('should create an instance of Repository', function() {
        // TODO: update the code to test Repository
        expect(instance).to.be.a(dcs.Repository);
      });

      it('should have the property allowMergeCommits (base name: "allow_merge_commits")', function() {
        // TODO: update the code to test the property allowMergeCommits
        expect(instance).to.have.property('allowMergeCommits');
        // expect(instance.allowMergeCommits).to.be(expectedValueLiteral);
      });

      it('should have the property allowRebase (base name: "allow_rebase")', function() {
        // TODO: update the code to test the property allowRebase
        expect(instance).to.have.property('allowRebase');
        // expect(instance.allowRebase).to.be(expectedValueLiteral);
      });

      it('should have the property allowRebaseExplicit (base name: "allow_rebase_explicit")', function() {
        // TODO: update the code to test the property allowRebaseExplicit
        expect(instance).to.have.property('allowRebaseExplicit');
        // expect(instance.allowRebaseExplicit).to.be(expectedValueLiteral);
      });

      it('should have the property allowSquashMerge (base name: "allow_squash_merge")', function() {
        // TODO: update the code to test the property allowSquashMerge
        expect(instance).to.have.property('allowSquashMerge');
        // expect(instance.allowSquashMerge).to.be(expectedValueLiteral);
      });

      it('should have the property archived (base name: "archived")', function() {
        // TODO: update the code to test the property archived
        expect(instance).to.have.property('archived');
        // expect(instance.archived).to.be(expectedValueLiteral);
      });

      it('should have the property avatarUrl (base name: "avatar_url")', function() {
        // TODO: update the code to test the property avatarUrl
        expect(instance).to.have.property('avatarUrl');
        // expect(instance.avatarUrl).to.be(expectedValueLiteral);
      });

      it('should have the property books (base name: "books")', function() {
        // TODO: update the code to test the property books
        expect(instance).to.have.property('books');
        // expect(instance.books).to.be(expectedValueLiteral);
      });

      it('should have the property catalog (base name: "catalog")', function() {
        // TODO: update the code to test the property catalog
        expect(instance).to.have.property('catalog');
        // expect(instance.catalog).to.be(expectedValueLiteral);
      });

      it('should have the property checkingLevel (base name: "checking_level")', function() {
        // TODO: update the code to test the property checkingLevel
        expect(instance).to.have.property('checkingLevel');
        // expect(instance.checkingLevel).to.be(expectedValueLiteral);
      });

      it('should have the property cloneUrl (base name: "clone_url")', function() {
        // TODO: update the code to test the property cloneUrl
        expect(instance).to.have.property('cloneUrl');
        // expect(instance.cloneUrl).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "created_at")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property defaultBranch (base name: "default_branch")', function() {
        // TODO: update the code to test the property defaultBranch
        expect(instance).to.have.property('defaultBranch');
        // expect(instance.defaultBranch).to.be(expectedValueLiteral);
      });

      it('should have the property defaultMergeStyle (base name: "default_merge_style")', function() {
        // TODO: update the code to test the property defaultMergeStyle
        expect(instance).to.have.property('defaultMergeStyle');
        // expect(instance.defaultMergeStyle).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property empty (base name: "empty")', function() {
        // TODO: update the code to test the property empty
        expect(instance).to.have.property('empty');
        // expect(instance.empty).to.be(expectedValueLiteral);
      });

      it('should have the property externalTracker (base name: "external_tracker")', function() {
        // TODO: update the code to test the property externalTracker
        expect(instance).to.have.property('externalTracker');
        // expect(instance.externalTracker).to.be(expectedValueLiteral);
      });

      it('should have the property externalWiki (base name: "external_wiki")', function() {
        // TODO: update the code to test the property externalWiki
        expect(instance).to.have.property('externalWiki');
        // expect(instance.externalWiki).to.be(expectedValueLiteral);
      });

      it('should have the property fork (base name: "fork")', function() {
        // TODO: update the code to test the property fork
        expect(instance).to.have.property('fork');
        // expect(instance.fork).to.be(expectedValueLiteral);
      });

      it('should have the property forksCount (base name: "forks_count")', function() {
        // TODO: update the code to test the property forksCount
        expect(instance).to.have.property('forksCount');
        // expect(instance.forksCount).to.be(expectedValueLiteral);
      });

      it('should have the property fullName (base name: "full_name")', function() {
        // TODO: update the code to test the property fullName
        expect(instance).to.have.property('fullName');
        // expect(instance.fullName).to.be(expectedValueLiteral);
      });

      it('should have the property hasIssues (base name: "has_issues")', function() {
        // TODO: update the code to test the property hasIssues
        expect(instance).to.have.property('hasIssues');
        // expect(instance.hasIssues).to.be(expectedValueLiteral);
      });

      it('should have the property hasProjects (base name: "has_projects")', function() {
        // TODO: update the code to test the property hasProjects
        expect(instance).to.have.property('hasProjects');
        // expect(instance.hasProjects).to.be(expectedValueLiteral);
      });

      it('should have the property hasPullRequests (base name: "has_pull_requests")', function() {
        // TODO: update the code to test the property hasPullRequests
        expect(instance).to.have.property('hasPullRequests');
        // expect(instance.hasPullRequests).to.be(expectedValueLiteral);
      });

      it('should have the property hasWiki (base name: "has_wiki")', function() {
        // TODO: update the code to test the property hasWiki
        expect(instance).to.have.property('hasWiki');
        // expect(instance.hasWiki).to.be(expectedValueLiteral);
      });

      it('should have the property htmlUrl (base name: "html_url")', function() {
        // TODO: update the code to test the property htmlUrl
        expect(instance).to.have.property('htmlUrl');
        // expect(instance.htmlUrl).to.be(expectedValueLiteral);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property ignoreWhitespaceConflicts (base name: "ignore_whitespace_conflicts")', function() {
        // TODO: update the code to test the property ignoreWhitespaceConflicts
        expect(instance).to.have.property('ignoreWhitespaceConflicts');
        // expect(instance.ignoreWhitespaceConflicts).to.be(expectedValueLiteral);
      });

      it('should have the property internal (base name: "internal")', function() {
        // TODO: update the code to test the property internal
        expect(instance).to.have.property('internal');
        // expect(instance.internal).to.be(expectedValueLiteral);
      });

      it('should have the property internalTracker (base name: "internal_tracker")', function() {
        // TODO: update the code to test the property internalTracker
        expect(instance).to.have.property('internalTracker');
        // expect(instance.internalTracker).to.be(expectedValueLiteral);
      });

      it('should have the property language (base name: "language")', function() {
        // TODO: update the code to test the property language
        expect(instance).to.have.property('language');
        // expect(instance.language).to.be(expectedValueLiteral);
      });

      it('should have the property mirror (base name: "mirror")', function() {
        // TODO: update the code to test the property mirror
        expect(instance).to.have.property('mirror');
        // expect(instance.mirror).to.be(expectedValueLiteral);
      });

      it('should have the property mirrorInterval (base name: "mirror_interval")', function() {
        // TODO: update the code to test the property mirrorInterval
        expect(instance).to.have.property('mirrorInterval');
        // expect(instance.mirrorInterval).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property openIssuesCount (base name: "open_issues_count")', function() {
        // TODO: update the code to test the property openIssuesCount
        expect(instance).to.have.property('openIssuesCount');
        // expect(instance.openIssuesCount).to.be(expectedValueLiteral);
      });

      it('should have the property openPrCounter (base name: "open_pr_counter")', function() {
        // TODO: update the code to test the property openPrCounter
        expect(instance).to.have.property('openPrCounter');
        // expect(instance.openPrCounter).to.be(expectedValueLiteral);
      });

      it('should have the property originalUrl (base name: "original_url")', function() {
        // TODO: update the code to test the property originalUrl
        expect(instance).to.have.property('originalUrl');
        // expect(instance.originalUrl).to.be(expectedValueLiteral);
      });

      it('should have the property owner (base name: "owner")', function() {
        // TODO: update the code to test the property owner
        expect(instance).to.have.property('owner');
        // expect(instance.owner).to.be(expectedValueLiteral);
      });

      it('should have the property parent (base name: "parent")', function() {
        // TODO: update the code to test the property parent
        expect(instance).to.have.property('parent');
        // expect(instance.parent).to.be(expectedValueLiteral);
      });

      it('should have the property permissions (base name: "permissions")', function() {
        // TODO: update the code to test the property permissions
        expect(instance).to.have.property('permissions');
        // expect(instance.permissions).to.be(expectedValueLiteral);
      });

      it('should have the property _private (base name: "private")', function() {
        // TODO: update the code to test the property _private
        expect(instance).to.have.property('_private');
        // expect(instance._private).to.be(expectedValueLiteral);
      });

      it('should have the property releaseCounter (base name: "release_counter")', function() {
        // TODO: update the code to test the property releaseCounter
        expect(instance).to.have.property('releaseCounter');
        // expect(instance.releaseCounter).to.be(expectedValueLiteral);
      });

      it('should have the property size (base name: "size")', function() {
        // TODO: update the code to test the property size
        expect(instance).to.have.property('size');
        // expect(instance.size).to.be(expectedValueLiteral);
      });

      it('should have the property sshUrl (base name: "ssh_url")', function() {
        // TODO: update the code to test the property sshUrl
        expect(instance).to.have.property('sshUrl');
        // expect(instance.sshUrl).to.be(expectedValueLiteral);
      });

      it('should have the property starsCount (base name: "stars_count")', function() {
        // TODO: update the code to test the property starsCount
        expect(instance).to.have.property('starsCount');
        // expect(instance.starsCount).to.be(expectedValueLiteral);
      });

      it('should have the property subject (base name: "subject")', function() {
        // TODO: update the code to test the property subject
        expect(instance).to.have.property('subject');
        // expect(instance.subject).to.be(expectedValueLiteral);
      });

      it('should have the property template (base name: "template")', function() {
        // TODO: update the code to test the property template
        expect(instance).to.have.property('template');
        // expect(instance.template).to.be(expectedValueLiteral);
      });

      it('should have the property title (base name: "title")', function() {
        // TODO: update the code to test the property title
        expect(instance).to.have.property('title');
        // expect(instance.title).to.be(expectedValueLiteral);
      });

      it('should have the property updatedAt (base name: "updated_at")', function() {
        // TODO: update the code to test the property updatedAt
        expect(instance).to.have.property('updatedAt');
        // expect(instance.updatedAt).to.be(expectedValueLiteral);
      });

      it('should have the property watchersCount (base name: "watchers_count")', function() {
        // TODO: update the code to test the property watchersCount
        expect(instance).to.have.property('watchersCount');
        // expect(instance.watchersCount).to.be(expectedValueLiteral);
      });

      it('should have the property website (base name: "website")', function() {
        // TODO: update the code to test the property website
        expect(instance).to.have.property('website');
        // expect(instance.website).to.be(expectedValueLiteral);
      });

    });
  });

}));
