/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.dcs);
  }
}(this, function(expect, dcs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new dcs.NotificationApi();
  });

  describe('(package)', function() {
    describe('NotificationApi', function() {
      describe('notifyGetList', function() {
        it('should call notifyGetList successfully', function(done) {
          // TODO: uncomment, update parameter values for notifyGetList call and complete the assertions
          /*
          var opts = {};

          instance.notifyGetList(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(dcs.NotificationThread);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('notifyGetRepoList', function() {
        it('should call notifyGetRepoList successfully', function(done) {
          // TODO: uncomment, update parameter values for notifyGetRepoList call and complete the assertions
          /*
          var opts = {};

          instance.notifyGetRepoList(owner, repo, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(dcs.NotificationThread);
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('notifyGetThread', function() {
        it('should call notifyGetThread successfully', function(done) {
          // TODO: uncomment, update parameter values for notifyGetThread call and complete the assertions
          /*

          instance.notifyGetThread(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(dcs.NotificationThread);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('notifyNewAvailable', function() {
        it('should call notifyNewAvailable successfully', function(done) {
          // TODO: uncomment notifyNewAvailable call and complete the assertions
          /*

          instance.notifyNewAvailable(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(dcs.NotificationCount);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('notifyReadList', function() {
        it('should call notifyReadList successfully', function(done) {
          // TODO: uncomment, update parameter values for notifyReadList call
          /*
          var opts = {};

          instance.notifyReadList(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('notifyReadRepoList', function() {
        it('should call notifyReadRepoList successfully', function(done) {
          // TODO: uncomment, update parameter values for notifyReadRepoList call
          /*
          var opts = {};

          instance.notifyReadRepoList(owner, repo, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('notifyReadThread', function() {
        it('should call notifyReadThread successfully', function(done) {
          // TODO: uncomment, update parameter values for notifyReadThread call
          /*
          var opts = {};

          instance.notifyReadThread(id, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
