/*
 * DCS (Gitea) API.
 * This documentation describes the DCS (Gitea) API.
 *
 * OpenAPI spec version: 1.15.6a+dcs
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.30
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.dcs);
  }
}(this, function(expect, dcs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new dcs.SettingsApi();
  });

  describe('(package)', function() {
    describe('SettingsApi', function() {
      describe('getGeneralAPISettings', function() {
        it('should call getGeneralAPISettings successfully', function(done) {
          // TODO: uncomment getGeneralAPISettings call and complete the assertions
          /*

          instance.getGeneralAPISettings(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(dcs.GeneralAPISettings);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getGeneralAttachmentSettings', function() {
        it('should call getGeneralAttachmentSettings successfully', function(done) {
          // TODO: uncomment getGeneralAttachmentSettings call and complete the assertions
          /*

          instance.getGeneralAttachmentSettings(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(dcs.GeneralAttachmentSettings);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getGeneralRepositorySettings', function() {
        it('should call getGeneralRepositorySettings successfully', function(done) {
          // TODO: uncomment getGeneralRepositorySettings call and complete the assertions
          /*

          instance.getGeneralRepositorySettings(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(dcs.GeneralRepoSettings);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getGeneralUISettings', function() {
        it('should call getGeneralUISettings successfully', function(done) {
          // TODO: uncomment getGeneralUISettings call and complete the assertions
          /*

          instance.getGeneralUISettings(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(dcs.GeneralUISettings);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
